name: Smoke test
on: [push, pull_request]
jobs:
  ubuntu:
    strategy:
      matrix:
          version: ['8.1']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PhD
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.version}}

      - name: List packages and formats
        run: php render.php --list

      - name: Get run-test.php
        run: wget https://github.com/php/php-src/blob/master/run-tests.php

      - name: Run tests
        run: php run-tests.php --help
